config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :genres

  root "pages#show", page: "home"
  get "/pages/:page" => "pages#show"

  resources :ebooks
  resources :books
  resources :authors

end

app/models/book.rb
class Book < ActiveRecord::Base
  has_many :book_by_authors, inverse_of: :book, dependent: :destroy
  has_many :authors, through: :book_by_authors
  has_many :book_by_genres, inverse_of: :book, autosave: true, dependent: :destroy
  has_many :genres, through: :book_by_genres
  has_many :ebooks, inverse_of: :book, dependent: :destroy

  has_attached_file :cover, styles: { medium: "200x300", thumb: "100x150" }, default_url: "/images/no_cover_:style.gif"
  validates_attachment_content_type :cover, content_type: /\Aimage\/.*\z/

  accepts_nested_attributes_for :book_by_authors, allow_destroy: true
  accepts_nested_attributes_for :book_by_genres, allow_destroy: true
  accepts_nested_attributes_for :ebooks, allow_destroy: true

  validates_associated :book_by_authors
  validates_associated :book_by_genres
  validates_associated :ebooks
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!, only: [:new, :edit, :create, :update, :destroy]
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  # GET /books
  # GET /books.json
  def index
    # 8 books per page
    @books = Book.page(params[:page]).per(8)
  end

  # GET /books/1
  # GET /books/1.json
  def show
    respond_to do |format|
      format.js
      format.html
    end
  end

  # GET /books/new
  def new
    @book = Book.new
    @book.book_by_genres.build
    @book.book_by_authors.build
    @book.ebooks.build
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)
    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:title, :isbn, :description, :cover, book_by_genres_attributes: [:id, :genre_id, :_destroy])
    end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_book.html.erb
<!-- Book box -->
<div id="book-<%= book.id %>" class="item book">
  <div class="well">
    <h3 class="title"><%= book.title %></h3>
    <img src="<%= book.cover.url(:medium) %>" alt="'<%= book.title %>' Cover">
    <p class="caption">
      <%= link_to "Read Now!", "#", class: "btn btn-primary" if user_signed_in? && current_user.books.find_by_id(book.id) %>
      <%= link_to "More Info", book_url(book), remote: true, class: "btn btn-info" %>
    </p>
  </div>
</div>

app/views/books/_book_modal.html.erb
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h3 class="modal-title"><%= book.title %></h3>
	<h4 class="modal-title text-capitalize">
          <span><%= book.authors.collect{|a| a.name}.join(", ") %></span>
          <span class="pull-right"><%= book.genres.collect{|g| g.name}.join(", ") %></span>
	</h4>
      </div>
      <div class="modal-body">
        <img class="pull-left img-responsive cover" src="<%= book.cover.url(:medium) %>" alt="'<%= book.title %>' Cover">
        <span><%= book.description.gsub("\n","<br>").html_safe %></span>
        <span class="clearfix"></span>
      </div>
      <div class="modal-footer">
        <%= link_to "Read Now!", "#", class: "btn btn-primary" if user_signed_in? && current_user.books.find_by_id(book.id) %>
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>

app/views/books/_form.html.erb
<%= form_for @book  do |f| %>
  <%= render 'layouts/error_messages', object: @book %>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title, class: "form-control" %>
  </div>
  <div class="field">
    <%= f.label :isbn %><br>
    <%= f.text_field :isbn, class: "form-control" %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description, class: "form-control" %>
  </div>
  <div class="field">
    <%= f.label :cover %><br>
    <%= f.file_field :cover, class: "btn btn-large btn-file btn-primary" %>
  </div>
  <div class="field">
    <%= f.label :genres %><br>
    <%= f.fields_for :book_by_genres do |g| %>
      <%= g.collection_select :genre_id, Genre.order(:name), :id, :name, permit_blank: true %>
    <% end %>
  </div>
  <div class="actions">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<%= render 'form' %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
  <p id="notice"><%= notice %></p>

  <!-- Jumbotron Header
  <header class="jumbotron hero-spacer">
    <h1>A Warm Welcome!</h1>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ipsa, ipsam, eligendi, in quo sunt possimus non incidunt odit vero aliquid similique quaerat nam nobis illo aspernatur vitae fugiat numquam repellat.</p>
    <p><a class="btn btn-primary btn-large">Call to action!</a></p>
  </header>
  <hr>
  -->

  <!-- Modal Box -->
  <div id="bookModal" class="modal fade text-justify" role="dialog" aria-labelledby="bookModal" aria-hidden="true">
    <div class="modal-dialog">
      <!-- Modal content -->
      <div id="bookModal-content" class="modal-content">
      </div>
    </div>
  </div>
  <!-- Modal Box -->

  <!-- Books -->
  <div id="books" class="row text-center">
    <div class="page">
      <%= render @books %>
    </div>
  </div>
  <!-- Books -->

  <br>

  <div id="books-pagination">
    <%= paginate @books %>
  </div>

  <%= link_to 'New Book', new_book_path if user_signed_in? %>

app/views/books/index.js.erb
$("#books").append("<div class='page'><%= escape_javascript(render(@books)) %><div>");

app/views/books/new.html.erb
<h1>New Book</h1>

<%= render 'form' %>

<%= link_to 'Back', books_path %>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @book.title %>
</p>

<p>
  <strong>Isbn:</strong>
  <%= @book.isbn %>
</p>

<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Back', books_path %>

app/views/books/show.js.erb
$("#bookModal-content").html("<%= escape_javascript(render partial: 'book_modal', locals: { book: @book } ) %>");
$("#bookModal").modal('show');