config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :genres

  root "pages#show", page: "home"
  get "/pages/:page" => "pages#show"

  resources :ebooks
  resources :books
  resources :authors

end

app/models/ebook.rb
class Ebook < ActiveRecord::Base
  belongs_to :book
  has_many :ebook_by_users, dependent: :destroy
  has_many :users, through: :ebook_by_users

  has_attached_file :ebook, url: '/:class/:id/download/:style.:extension',
                            path: ':rails_root/private/:class/:attachment/:id_partition/:style/:filename'

  validates_attachment_content_type :ebook, content_type: ["application/vnd.amazon.ebook",
							   "application/x-mobipocket-ebook",
							   "application/epub+zip",
                                                           "application/pdf", "text/plain"]
  validates :book_id, presence: true

  # Read epub ebook meta and update book info
  def read_epub_meta ebook_file=nil
    meta = nil
    mybook = self.book
    file = ebook_file
    begin
      Zip::File.open(file) do |zf|
        container = Nokogiri::XML(zf.read("META-INF/container.xml")).remove_namespaces! if zf.find_entry("META-INF/container.xml")
        opf_file = container.xpath('//rootfile').first.attributes['full-path'].value if container
        meta = Nokogiri::XML(zf.read(opf_file)) if opf_file && zf.find_entry(opf_file)
        meta.remove_namespaces! if meta
        if meta
          mybook ||= Book.new
          # Pilla los datos basicos (identificativos) del libro
          mybook.title = meta.xpath('//title').text
          mybook.description = meta.xpath('//description').text
          meta.xpath('//creator').to_a.each do |author|
            author_name = Author.get_name(author.text)
            mybook.authors << Author.find_or_create_by(name: author_name) if author_name
          end
	  meta.xpath('//subject').to_a.each do |genre|
            genre_name = Genre.get_name(genre.text)
            mybook.genres << Genre.find_or_create_by(name: genre_name) if genre_name
	  end
          # Another book data 
	  #mybook.lang = meta.xpath('//language').text
          #puts "------> LANG: " + meta.xpath('//language').text
          #puts "------> PUBLISHERS: " + meta.xpath('//publisher').to_a.collect {|c| c.text}.inspect
          # Get book cover
          cover_name = "cover-image"
          meta.xpath("//meta[@name='cover']").each do |meta_values|
            cover_name = meta_values.attributes["content"] if meta_values.attributes["name"].to_s == "cover"
          end
          cover = meta.xpath("//item[@id ='" + cover_name + "']").first if meta
          image = cover.attributes["href"].value if cover && cover.attributes["href"]
          if image
            # Copy cover from epub
            tmp_cover = Tempfile.new("cover")
            File.open(tmp_cover, "wb") { |f| f.write(zf.read((File.dirname(opf_file) + "/" + image).gsub("./",""))) }
            # Upload cover to book
            mybook.cover = File.open(tmp_cover, 'rb')
          end
        end
      end
    rescue => e
      errors.add :base, "#{e.class.name} : #{e.message}"
    end
    return mybook
  end
end

app/controllers/ebooks_controller.rb
class EbooksController < ApplicationController
  before_action :authenticate_user!
  before_action :set_ebook, only: [:show, :edit, :update, :destroy]

  # GET /ebooks
  # GET /ebooks.json
  def index
    @ebooks = Ebook.all
  end

  # GET /ebooks/1
  # GET /ebooks/1.json
  def show
  end

  # GET /ebooks/new
  def new
    @ebook = Ebook.new
  end

  # GET /ebooks/1/edit
  def edit
  end

  # POST /ebooks
  # POST /ebooks.json
  def create
    @ebook = Ebook.new(ebook_params)

    respond_to do |format|
      if @ebook.save
        format.html { redirect_to @ebook, notice: 'Ebook was successfully created.' }
        format.json { render :show, status: :created, location: @ebook }
      else
        format.html { render :new }
        format.json { render json: @ebook.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ebooks/1
  # PATCH/PUT /ebooks/1.json
  def update
    respond_to do |format|
      if @ebook.update(ebook_params)
        format.html { redirect_to @ebook, notice: 'Ebook was successfully updated.' }
        format.json { render :show, status: :ok, location: @ebook }
      else
        format.html { render :edit }
        format.json { render json: @ebook.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ebooks/1
  # DELETE /ebooks/1.json
  def destroy
    @ebook.destroy
    respond_to do |format|
      format.html { redirect_to ebooks_url, notice: 'Ebook was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ebook
      @ebook = Ebook.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ebook_params
      params.require(:ebook).permit(:book_id, :ebook)
    end
end

app/helpers/ebooks_helper.rb
module EbooksHelper
end

app/views/ebooks/_form.html.erb
<%= form_for(@ebook) do |f| %>
  <% if @ebook.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ebook.errors.count, "error") %> prohibited this ebook from being saved:</h2>

      <ul>
      <% @ebook.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :book_id %><br>
    <%= f.number_field :book_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ebooks/edit.html.erb
<h1>Editing Ebook</h1>

<%= render 'form' %>

<%= link_to 'Show', @ebook %> |
<%= link_to 'Back', ebooks_path %>

app/views/ebooks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Ebooks</h1>

<table>
  <thead>
    <tr>
      <th>Book</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ebooks.each do |ebook| %>
      <tr>
        <td><%= ebook.book_id %></td>
        <td><%= link_to 'Show', ebook %></td>
        <td><%= link_to 'Edit', edit_ebook_path(ebook) %></td>
        <td><%= link_to 'Destroy', ebook, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ebook', new_ebook_path %>

app/views/ebooks/new.html.erb
<h1>New Ebook</h1>

<%= render 'form' %>

<%= link_to 'Back', ebooks_path %>

app/views/ebooks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Book:</strong>
  <%= @ebook.book_id %>
</p>

<%= link_to 'Edit', edit_ebook_path(@ebook) %> |
<%= link_to 'Back', ebooks_path %>